name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu]
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade packaging tools
        run: python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/main.txt
          python -m pip install -e .
      - name: Run tests
        run: python -m pytest -v tests
